services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./src/main/resources/prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
#    networks:
#      - back-tier
    restart: always
